# DO NOT EDIT THIS FILE!
#
# Python module Action generated by omniidl

import omniORB
omniORB.updateModule("Action")

# ** 1. Stub files contributing to this module
import ActionManage_idl

# ** 2. Sub-modules

# ** 3. End
