# Python stubs generated by omniidl from idl/ActionManage.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "Action"
#
__name__ = "Action"
_0_Action = omniORB.openModule("Action", r"idl/ActionManage.idl")
_0_Action__POA = omniORB.openModule("Action__POA", r"idl/ActionManage.idl")


# interface ActionManage
_0_Action._d_ActionManage = (omniORB.tcInternal.tv_objref, "IDL:Action/ActionManage:1.0", "ActionManage")
omniORB.typeMapping["IDL:Action/ActionManage:1.0"] = _0_Action._d_ActionManage
_0_Action.ActionManage = omniORB.newEmptyClass()
class ActionManage :
    _NP_RepositoryId = _0_Action._d_ActionManage[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_Action.ActionManage = ActionManage
_0_Action._tc_ActionManage = omniORB.tcInternal.createTypeCode(_0_Action._d_ActionManage)
omniORB.registerType(ActionManage._NP_RepositoryId, _0_Action._d_ActionManage, _0_Action._tc_ActionManage)

# ActionManage operations and attributes
ActionManage._d_read = (((omniORB.tcInternal.tv_string,0), ), (), None)

# ActionManage object reference
class _objref_ActionManage (CORBA.Object):
    _NP_RepositoryId = ActionManage._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def read(self, *args):
        return self._obj.invoke("read", _0_Action.ActionManage._d_read, args)

omniORB.registerObjref(ActionManage._NP_RepositoryId, _objref_ActionManage)
_0_Action._objref_ActionManage = _objref_ActionManage
del ActionManage, _objref_ActionManage

# ActionManage skeleton
__name__ = "Action__POA"
class ActionManage (PortableServer.Servant):
    _NP_RepositoryId = _0_Action.ActionManage._NP_RepositoryId


    _omni_op_d = {"read": _0_Action.ActionManage._d_read}

ActionManage._omni_skeleton = ActionManage
_0_Action__POA.ActionManage = ActionManage
omniORB.registerSkeleton(ActionManage._NP_RepositoryId, ActionManage)
del ActionManage
__name__ = "Action"

#
# End of module "Action"
#
__name__ = "ActionManage_idl"

_exported_modules = ( "Action", )

# The end.
